pipeline:
  name: feat15
  identifier: feat15
  projectIdentifier: demo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dfa
        identifier: dfa
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
